host: 'localhost'
port: '3306'
db: 'seichiassist'
id: 'root'
pw: 'uzFpcJxYcPYArqBT'
defaultmineamount: '3'
minutespeedamount: '0.01'
onlineplayersamount: '0.5'
presentinterval: '1000'
dualbreaklevel: '10'
trialbreaklevel: '20'
explosionlevel: '30'
thunderstormlevel: '40'
blizzardlevel: '50'
meteolevel: '60'
gravitylevel: '100'
dropexplevel1: '6'
dropexplevel2: '10'
dropexplevel3: '16'
dropexplevel4: '24'
dropexplevel5: '34'
dropexplevel6: '46'
dropexplevel7: '60'
dropexplevel8: '76'
dropexplevel9: '94'
dropexplevel10: '114'
passiveportalinventorylevel: '16'
dokodemoenderlevel: '25'
minestacklevel1: '12'
minestacklevel2: '17'
minestacklevel3: '22'
minestacklevel4: '27'
minestacklevel5: '32'
minestacklevel6: '37'
minestacklevel7: '42'
minestacklevel8: '47'
minestacklevel9: '52'
minestacklevel10: '57'
lv1message: "整地鯖では整地をするとレベルが上がり、様々な恩恵が受けられます。\n初めての方は整地ワールドで掘ってレベルを上げてみましょう！\n木の棒を右クリックしてメニューを開き右上のビーコンボタンをクリック！"
lv2message: "おめでとうございます！最初のレベルアップです！\nレベル8に到達すると整地するだけで経験値がもらえるようになります。"
lv3message: "やけに早く掘れる気がする…？それは仕様です＾＾\n整地鯖では接続人数や採掘量に応じて採掘速度にブーストが掛かります。"
lv4message: "整地鯖では死んでもロストしません。気軽に冒険、整地してくださいね。\nそういえば当鯖の「ルール」もう確認しましたか？\n手遅れになる前に確認しておきましょうネ。木の棒メニューからどうぞ。"
lv5message: "Dynmapでどこに誰がいるのか、何があるのかなどを見ることができます。\nURLはこちら→http://mc.seichi.click:8123"
lv6message: "ブランチマイニングは資源ワールドでお願いします。\nスポーンワールドから行くことが出来ます。行き方覚えてますか？\n木の棒メニューのビーコンボタンをクリックするとすぐ行けますよ！"
lv7message: "あと300ブロックほど整地するとガチャ券を獲得できます！\nガチャ券を右クリックすると豪華景品が獲得できるかも？"
lv8message: "おめでとう！新しいパッシブスキル[追加経験値獲得]を解除しました。\n特定のブロック破壊で確率で追加経験値を獲得できるようになりました！\nレベル10に到達すると初めてのアクティブスキルが解禁します！"
lv9message: "整地鯖をもっと良くするために、是非JPMCSに投票をお願いします。\n1日1回投票出来ます。投票すると様々な特典を受け取れます！\nURLはこちら→https://minecraft.jp/servers/seichi.click/vote"
lv10message: "初めてのアクティブスキル[デュアルブレイク]を解除しました！\nピッケル、シャベル、斧を持った状態でShift+右クリックして下さい。\nレベル12に到達するとMineStack機能が使えるようになります。"
lv11message: "そろそろ家建てません…？自分の家はメインワールドで建てることができます。\n他人の保護の無い所に保護を設定してから建てましょう。\n保護方法は公式wikiに詳しい説明があります。木の棒メニューからどうぞ。\n自分のチェストは設定した保護内に置けば自動でロックされます。"
lv12message: "MineStack機能を解除しました！木の棒メニューから呼び出せます。\n対象ブロックを無限にスタック出来、いつでも取り出せます。\nスタック出来るブロックはレベルを上げると増えていきます。\nレベル16に到達すると四次元ポケットが使えるようになります。"
lv13message: "建築の時など、採掘速度のブースト効果が邪魔な時は\n木の棒メニューから効果のONとOFFを変更できます。"
lv14message: "「ガチャ券がイチイチ地面に落っこちるのがうざい！」\nって人に朗報です。木の棒メニューからガチャ券の取得方法を変更できます。"
lv15message: "家を建てたら木の棒メニューからホームポイントを設定しておきましょう。\nどこからでもクリック1つで自宅へ瞬間移動できますよ！"
lv16message: "新しいパッシブスキル[4次元ポケット]を解除しました！\n四次元ポケットは木の棒メニューから開くことが出来ます。\nレベルを上げるとポケットの容量が増えていきます。"
lv17message: "MineStack機能の対象ブロックが増えました！\n新たに砂利がスタックされるようになります。"
lv18message: "整地の際に獲得できる経験値量が増えました。\n経験値量は10レベルごとに増加し、スキルがより長く使えるようになります！"
lv20message: "新しいアクティブスキル[トリアルブレイク]を解除しました！\n棒を持って右クリックするとスキルを切り替えられます。"
lv22message: "MineStack機能の対象ブロックが増えました！\n新たに石がスタックされるようになります。"
lv25message: "どこでもエンダーチェスト機能を解除しました！\n木の棒メニューから呼び出せます。"
lv27message: "MineStack機能の対象ブロックが増えました！\n新たに砂と砂岩がスタックされるようになります。"
lv28message: "整地の際に獲得できる経験値量が増えました。"
lv30message: "新しいアクティブスキル[エクスプロージョン]を解除しました！\n破壊範囲が広くなっています。誤爆に注意しましょう。"
lv32message: "MineStack機能の対象ブロックが増えました！\n新たにネザーラックがスタックされるようになります。"
lv37message: "MineStack機能の対象ブロックが増えました！\n新たにソウルサンドとマグマブロックがスタックされるようになります。"
lv38message: "整地の際に獲得できる経験値量が増えました。"
lv40message: "新しいアクティブスキル[サンダーストーム]を解除しました！"
lv42message: "MineStack機能の対象ブロックが増えました！\n新たにエンドストーンがスタックされるようになります。"
lv47message: "MineStack機能の対象ブロックが増えました！\n新たに石炭と石炭鉱石がスタックされるようになります。"
lv48message: "整地の際に獲得できる経験値量が増えました。"
lv50message: "新しいアクティブスキル[ブリザード]を解除しました！"
lv52message: "MineStack機能の対象ブロックが増えました！\n新たに鉄鉱石がスタックされるようになります。"
lv57message: "MineStack機能の対象ブロックが増えました！\n新たにクォーツとクォーツ鉱石がスタックされるようになります。"
lv58message: "整地の際に獲得できる経験値量が増えました。"
lv60message: "新しいアクティブスキル[メテオ]を解除しました！"
lv68message: "整地の際に獲得できる経験値量が増えました。"
lv78message: "整地の際に獲得できる経験値量が増えました。"
lv88message: "整地の際に獲得できる経験値量が増えました。"
lv98message: "整地の際に獲得できる経験値量が増えました。"
