defaultmineamount: '3'
minutespeedamount: '0.01'
onlineplayersamount: '0.5'
presentinterval: '1000'
activeminelevel: '10'
dropexplevel: '5'
lv1message: ''
lv2message: ''
lv3message: ''
lv4message: ''
lv5message: 'おめでとうございます！特定のブロック破壊で得られる経験値量が増えました！'
lv6message: ''
lv7message: ''
lv8message: ''
lv9message: ''
lv10message: 'おめでとうございます！経験値を消費して2段破壊ができるようになりました！  ダイヤピッケルを持った状態で右クリックすると切り替えられます！'
lv11message: ''
lv12message: ''
lv13message: ''
lv14message: ''
lv15message: ''
lv16message: ''
lv17message: ''
lv18message: ''
lv19message: ''
lv20message: ''
lv21message: ''
lv22message: ''
lv23message: ''
lv24message: ''
lv25message: ''
lv26message: ''
lv27message: ''
lv28message: ''
lv29message: ''
lv30message: ''
lv31message: ''
lv32message: ''
lv33message: ''
lv34message: ''
lv35message: ''
lv36message: ''
lv37message: ''
lv38message: ''
lv39message: ''
lv40message: ''
lv41message: ''
lv42message: ''
lv43message: ''
lv44message: ''
lv45message: ''
lv46message: ''
lv47message: ''
lv48message: ''
lv49message: ''
lv50message: ''
lv51message: ''
lv52message: ''
lv53message: ''
lv54message: ''
lv55message: ''
lv56message: ''
lv57message: ''
lv58message: ''
lv59message: ''
lv60message: ''
lv61message: ''
lv62message: ''
lv63message: ''
lv64message: ''
lv65message: ''
lv66message: ''
lv67message: ''
lv68message: ''
lv69message: ''
lv60message: ''

