# ------------実行間隔のパラメータ---------------
# 最も破壊量の多いプレイヤーを称賛する間隔(分）
no1playerinterval: '30'
# 上のメッセージ送信基準破壊量(1分につき）
defaultmineamount: '3'

# -------------採掘速度関連のパラメータ---------------
# 採掘した量に応じた採掘速度変化（1分につき）
minutespeedamount: '0.01'

# ログイン人数に応じた採掘速度変化(１人につき）
onlineplayersamount: '0.5'

# ----------ガチャ券関連のパラメータ-----------------
# ガチャ券配布間隔ブロック数
presentinterval: '1000'