version: '3.7'
services:
  spigot_a:
    build: ./docker/spigot
    image: spigot
  spigot_b:
    build: ./docker/spigot
    image: spigot
  bungeecord:
    build: ./docker/bungeecord
    ports:
      - 25565:25565

volumes:
  elasticsearch-data:
    driver: local


