name: SeichiAssist
main: com.github.unchama.seichiassist.SeichiAssist
version: 0.1.8

commands:
  gacha:
      description: This is a gacha command.
      usage: /<command> <add/list/remove/clear>
      permission: multiseichiplugin.seichi
      permission-message: You don't have <permission>
  seichi:
      description: This is a seichi command.
      usage: /<command> <playername> <duration(tick)> <amplifier(double)>
      permission: multiseichiplugin.seichi
      permission-message: You don't have <permission>
  ef:
      description: This is a Effect toggle command.
      usage: /<command> <smart>
      permission: multiseichiplugin.ef
      permission-message: You don't have <permission>