# seichiassist 設定ファイル
# このファイルを削除orリネームしてからサーバを起動するとデフォルトの設定ファイルが再生成されます(エラーが出たときは真っ先に試しましょう)

# MySQLデータベースへの接続設定
# xamppの設定を変えていなければデフォルトの値で問題ありません
host: 'localhost'
port: '3306'
db: 'seichiassist'
id: 'root'
pw: ''

# サーバ識別設定
# 複数サーバ構成にする場合はこの値をサーバごとに変更します
servernum: '1'

# 色々な設定、説明は割愛
defaultmineamount: '3'
minutespeedamount: '0.01'
onlineplayersamount: '0.5'
presentinterval: '1000'
dualbreaklevel: '10'
trialbreaklevel: '20'
explosionlevel: '30'
thunderstormlevel: '40'
blizzardlevel: '50'
meteolevel: '60'
gravitylevel: '100'
multipleidblockbreaklevel: '1'
dropexplevel1: '6'
dropexplevel2: '10'
dropexplevel3: '16'
dropexplevel4: '24'
dropexplevel5: '34'
dropexplevel6: '46'
dropexplevel7: '60'
dropexplevel8: '76'
dropexplevel9: '94'
dropexplevel10: '114'
passiveportalinventorylevel: '1'
dokodemoenderlevel: '25'

# MineStackの開放レベルの設定
minestacklevel1: '12'
minestacklevel2: '17'
minestacklevel3: '22'
minestacklevel4: '27'
minestacklevel5: '32'
minestacklevel6: '37'
minestacklevel7: '42'
minestacklevel8: '47'
minestacklevel9: '52'
minestacklevel10: '57'
minestacklevel11: '62'
minestacklevel12: '67'
minestacklevel13: '72'
minestacklevel14: '77'
minestacklevel15: '82'
minestacklevel16: '87'
minestacklevel17: '92'
minestacklevel18: '97'
minestacklevel19: '102'
minestacklevel20: '107'
minestacklevel21: '112'
minestacklevel22: '117'
minestacklevel23: '122'
minestacklevel24: '127'
minestacklevel25: '132'
minestacklevel26: '137'
minestacklevel27: '142'
minestacklevel28: '147'
minestacklevel29: '152'
minestacklevel30: '157'
minestacklevel31: '162'
minestacklevel32: '167'
minestacklevel33: '172'
minestacklevel34: '177'
minestacklevel35: '182'
minestacklevel36: '187'
minestacklevel37: '192'
minestacklevel38: '197'

# サブホームポイント数の設定
# 7以下に設定
subhomemax: 5

# 実績名の名称設定 -> Nicknames.scalaを参照すること

# デバッグモードの設定
# debugmode: 0=デバッグモードオフ, 1=デバッグモードオン
# 変更値を反映させるにはサーバを再起動するか/reloadしてください
debugmode: '0'

# デバッグモード(メビウス帽子専用)の設定
# debugmode: 0=デバッグモードオフ, 1=デバッグモードオン
# 変更値を反映させるにはサーバを再起動するか/reloadしてください
mebiusdebug: '0'

# ギガンティック→椎名林檎交換レートの設定
# デフォルト値はギガンティック1個につき椎名林檎4個
rategigantictoringo: '4'

# ギガンティック・フィーバーの効果継続時間を指定します。(単位:分)
gigantic_fever_minutes: 120

# グリッド式保護メニュー経由で保護が可能なワールド名一覧
# ここに記載されたワールド名ではworldguard.region.claimパーミッションが無くても
# グリッド式保護メニュー経由で保護が可能になります
GridProtectEnableWorld:
  - world_test

# グリッドで指定可能な最大ユニット合計数の設定
# (15ブロック=1ユニット)
## デフォルト値
GridLimitDefault: '32'
## ワールド毎の値(ここにないワールドはDefault値を見る)
GridLimitPerWorld:
  world: '16'
  world_2: '32'

#グリッド式保護のテンプレート保存最大数
GridTemplateKeepAmount: '5'

##自動再生成時の設定
#道のY座標
road_Y: 70
#道の長さ(チャンク単位)
road_length: 8
#道の上の空洞の高さ
space_height: 5
#道のブロックID
road_blockid: 98
#道のブロックダメージ値
road_blockdamage: 0
#再生成時のワールドサイズ
world_size: 2000

#貢献度1当たりのマナ増加量
contribute_added_mana: 10

#期間限定ログインイベント(ここの設定を変更することで毎年使いまわしが可能です。)
#日付は必ず"西暦4桁/月2桁/日2桁"で入力すること!!
LimitedLoginEvent:
  #開始日(この日からカウントされるようになります)
  EventStart: "2019/03/01"
  #終了日(この日が最後のカウント対象になります)
  EventEnd: "2019/03/31"

  #報酬設定
  #DAY0のデータは毎日配布されます
  #それ以外のデータは、期間内の累計ログイン数がその値になった日のみ配布されます
  #Itemで配布内容を、Amountで数量を指定します
  DAY0_Item: "1"
  DAY0_Amount: "30"
  DAY20_Item: "1"
  DAY20_Amount: "100"
  #Tips:[Item]内容一覧(追加・変更はコード修正が必要です)
  #"1":ガチャ券

#お正月イベント関連(ここの設定を変更することで毎年使いまわしが可能です。)
#日付は必ず"西暦4桁-月2桁-日2桁"で入力すること!!
NewYearEvent:
  #お正月用「年越し蕎麦」配布日
  GivingNewYearSobaDay: "2017-12-31"
  #お正月用「年越し蕎麦」Loreに記入される年
  NewYearSobaYear: "2017"
  #お年玉袋ドロップ開始日/終了日
  DropNewYearBagStartDay: "2018-01-01"
  DropNewYearBagEndDay: "2018-01-31"
  #お年玉袋ドロップ数(1/nブロック)
  NewYearBagDropProbability: 500
  #(お年玉袋ItemNBT識別用);基本的に来年度の年を入力してください。
  NewYear: "2018"
  #正月リンゴの使用可能期限
  NewYearAppleStartDay: "2018-01-01"
  NewYearAppleEndDay: "2018-02-07"

#GiganticBerserk
#1分間上限
GBLimit: 20

#各種URL
Url:
  official: "https://www.seichi.network/gigantic"
  rule: "https://www.seichi.network/rule"
  map: "https://www.seichi.network/map"
  jms: "https://minecraft.jp/servers/54d3529e4ddda180780041a7"

#Fly時の1分辺りの経験値消費量
flyexp: '50'

#ブロックを並べるスキル
blocklineup:
  level: '15'
  mana_mag: '0.0'
  minestack_level: '30'

#範囲設置スキル
ZoneSetSkill:
  level: '15'
  minestack: '30'

#スキルを使って並べた時のブロックカウント倍率
BlockCountMag: '0.2'

# MineStackブロック一括クラフト
minestack_BlockCraft:
  level1: '25'
  level2: '35'
  level3: '45'

#ブロック設置カウントの1分上限
BuildNum1minLimit: '256'
