version: 2.1

anchors:
  docker:
    gradle_docker: &sbt_docker
      docker:
        - image: circleci/openjdk:8u181-jdk
  workspace:
    save_workspace: &save_workspace
      persist_to_workspace:
        root: ./workspace
        paths:
          - '*'
    load_workspace: &load_workspace
      attach_workspace:
        at: '/tmp/workspace'
  cache:
    dependencies:
      save_cache: &save_dependencies
        paths:
          - ~/.ivy2/cache
          - ~/.m2
          - ~/.cache/coursier/v1
          - ~/.sbt
        key: sbt-repo-v3-{{ .Branch }}-{{ checksum "build.sbt" }}
      restore_cache: &restore_dependencies
        keys:
          - sbt-repo-v3-{{ .Branch }}-{{ checksum "build.sbt" }}
          - sbt-repo-v3-{{ .Branch }}-
          - sbt-repo-v3-
    build_cache:
      ## 圧縮時にタイムスタンプが丸められるため、
      ## オプション付きで圧縮をしたものをキャッシュとして保存しないと
      ## コンパイルがインクリメンタルになってくれない
      ## https://kurochan-note.hatenablog.jp/entry/2018/03/21/162929
      commands:
        - &archive_build_cache
          run:
            name: Archive build cache
            command: |
              mkdir -p .cache
              tar --format posix -cvf ~/.build_cache/cache_target.tar target/ > /dev/null
              tar --format posix -cvf ~/.build_cache/cache_project_target.tar project/target/ > /dev/null
        - &unarchive_build_cache
          run:
            name: Unarchive build cache
            command: |
              cat ~/.build_cache/cache_*.tar | tar xvf - -i > /dev/null
      save_cache: &save_build_cache
        ## 毎回ビルド結果をキャッシュする。次のビルドにて
        ##  build-cache-v3-{{ .Branch }}
        ## までが等しい最新のキャッシュが使われるから、コンパイルはインクリメンタルになる。
        paths:
          - ~/.build_cache
        key: build-cache-v3-{{ .Branch }}-{{ epoch }}

      restore_cache: &restore_build_cache
        ## ブランチ間でのビルドキャッシュ共有は行わない
        keys:
          - build-cache-v3-{{ .Branch }}-

jobs:
  build_and_test:
    <<: *sbt_docker
    working_directory: ~/repo
    steps:
      - checkout
      - *restore_dependencies
      - *restore_build_cache
      - *unarchive_build_cache

      - run: du -h --max-depth=2 ~
      - run: |
          ./sbt assembly && \
          mkdir -p workspace/builds && \
          cp target/build/**.jar workspace/builds && \
          rm -rf target/build

      - *save_workspace

      - *save_dependencies
      - *archive_build_cache
      - *save_build_cache
  deploy_debug:
    <<: *sbt_docker
    working_directory: ~/repo
    steps:
      - *load_workspace
      - run: du -h --max-depth=2 /tmp/workspace/builds
      - run: scp -v -oStrictHostKeyChecking=no -P $HOST_PORT /tmp/workspace/builds/**.jar $DEBUG_DEPLOY_TARGET_HOST
  deploy_production:
    <<: *sbt_docker
    working_directory: ~/repo
    steps:
      - *load_workspace
      - run: du -h --max-depth=2 /tmp/workspace/builds
      - run: scp -v -oStrictHostKeyChecking=no -P $HOST_PORT /tmp/workspace/builds/**.jar $PRODUCTION_DEPLOY_TARGET_HOST

workflows:
  version: 2
  test_and_build:
    jobs:
      - build_and_test
      - deploy_production:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
      - deploy_debug:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - develop
